name: keras2c-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.13.0
  - pydantic>=1.10,<2
  - tensorflow>=2.0
  - pytest>=7.4.4
  - pytest-cov>=4.1.0
  - codecov>=2.1.13
  - ruff
  - pip
  - pip:
      - keras
